### ISSUE TITLE
SDL/GLUT Issues with Arch Linux

### ISSUE THREAD

**Issue by fosskers** [metinsay/SkyKnight#1]
Hi there, got your game to compile. When I tried running it with `stack exec -- wingsuit`, I was told:

```
colin@yumi ~/c/h/S/wingsuit> stack exec -- wingsuit
wingsuit: user error (unknown GLUT entry glutInit)
```

Any ideas?

**Comment by tysonzero** [comment]
You will need `GLUT` installed on your system. This is a known (and should be in README) requirement, will add it to the README soon.

**Comment by fosskers** [comment]
For anyone running Arch Linux, I had to install (at least) `sdl2_mixer` for this to compile, and `freeglut` for this to run.
